repos:
  - repo: https://github.com/psf/black # run black to format code beofre commit
    rev: 23.12.1
    hooks:
      - id: black # hook id
        exclude: ^(.*/)?\..*$ # exclude hidden files

  - repo: https://github.com/pycqa/flake8
    rev: '6.1.0'  # pick a git hash / tag to point to
    hooks:
      - id: flake8 # hook id
        exclude: ^custom_accounts/migrations/  # exclude hidden files and folders

